-- CreateEnum
CREATE TYPE "MedicalExclusion" AS ENUM ('HEPATITIS_B', 'HEPATITIS_C', 'HIV_AIDS', 'CHAGAS', 'SYPHILIS', 'MALARIA', 'TUBERCULOSIS', 'CANCER', 'HEART_DISEASE', 'EPILEPSY', 'RECENT_TATTOO_PIERCING', 'RECENT_SURGERY', 'RECENT_PREGNANCY', 'HIGH_RISK_SEXUAL_BEHAVIOR', 'IV_DRUG_USE', 'OTHER');

-- AlterTable
ALTER TABLE "donors" ADD COLUMN     "allergies" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "medicalExclusions" "MedicalExclusion"[] DEFAULT ARRAY[]::"MedicalExclusion"[];

